---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO: Replace these with init scripts
- name: Restart object server
  shell: swift-init object-server restart || swift-init object-server restart

- name: Restart object auditor
  shell: swift-init object-auditor restart || swift-init object-auditor restart

- name: Restart object replicator
  shell: swift-init object-replicator restart || swift-init object-replicator restart

- name: Restart object updater
  shell: swift-init object-updater restart || swift-init object-updater restart
