---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: "swift container server configuration"
  template: >
    src="container-server.conf.j2"
    dest="/etc/swift/container-server.conf"
    owner={{ system_user }}
    mode=0644
  notify:
    - Restart container server
    - Restart container auditor
    - Restart container replicator
    - Restart container updater

- name: "Set container server to start at boot"
  cron: >
    name="Restart container-server on boot"
    special_time=reboot
    job="swift-init container-server start"

- name: "Set container auditor to start at boot"
  cron: >
    name="Restart container-auditor at boot"
    special_time=reboot
    job="swift-init container-auditor start"

- name: "Set container replicator to start at boot"
  cron: >
    name="Restart container-replicator at boot"
    special_time=reboot
    job="swift-init container-replicator start"

- name: "Set container updater to start at boot"
  cron: >
    name="Restart container-updater at boot"
    special_time=reboot
    job="swift-init container-updater start"
