---
- name: "make sure scripts directory exists"
  file: >
    state=directory
    path={{ item }}
    owner=root
    group=root
    mode=0755
  with_items:
    - /tmp/swift/rings
    - /tmp/swift/scripts

- name: "Copy the swift_rings.py file"
  copy: >
    src=swift_rings.py
    dest="/tmp/swift/scripts/swift_rings.py"

- name: "build rings"
  command: /usr/bin/python /tmp/swift/scripts/swift_rings.py -s /etc/rpc_deploy/rpc_user_config.yml
  args:
    chdir: /tmp/swift/rings/
